### ISSUE TITLE
Use openghg_defs for species and site info

### ISSUE THREAD

**Issue by joe-pitt** [openghg/openghg_inversions#146] opened 2024-06-24 12:38 UTC
At the moment openghg_inversions.utils.load_json uses the local openghg_inversions copy of species_info.json and site_info.json. This should be updated to import the json files from openghg_defs

**Comment by brendan-m-murphy** [comment] 2024-07-03 13:18
This is a duplicate of Issue #21 so I'm going to close it.

**Closed by brendan-m-murphy** 2024-07-03 13:18 UTC
